# Google App Engine configuration
# Alternative deployment option to Cloud Run

runtime: python312
instance_class: F1

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

# Environment variables
env_variables:
  ENVIRONMENT: 'production'
  LOG_LEVEL: 'INFO'
  API_BASE_URL: 'https://mu88.live/api/front/open/lottery/history/list/game'
  API_TIMEOUT: '30'
  CACHE_ENABLED: 'true'
  CACHE_TTL: '3600'

# Entry point
entrypoint: python -m app.main

# Health checks
liveness_check:
  path: "/health/live"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health/ready"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
