# Google Cloud Build configuration for CI/CD
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/xsbamien-telegram-bot:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/xsbamien-telegram-bot:latest'
      - '.'

  # Step 2: Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/xsbamien-telegram-bot:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/xsbamien-telegram-bot:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'xsbamien-telegram-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/xsbamien-telegram-bot:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,LOG_LEVEL=INFO'
      - '--set-secrets'
      - 'TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/xsbamien-telegram-bot:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/xsbamien-telegram-bot:latest'

# Build timeout
timeout: 1200s

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
