"""Add lo_3_so_history table

Revision ID: e9b97f837935
Revises: 001
Create Date: 2025-10-16 04:18:52.902470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b97f837935'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('favorite_provinces', sa.String(length=500), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('lo_3_so_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lottery_result_id', sa.Integer(), nullable=False),
    sa.Column('province_code', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('number', sa.String(length=3), nullable=False),
    sa.Column('prize_type', sa.String(length=10), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lottery_result_id'], ['lottery_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lo3so_draw_date_number', 'lo_3_so_history', ['draw_date', 'number'], unique=False)
    op.create_index('idx_lo3so_number_date', 'lo_3_so_history', ['number', 'draw_date'], unique=False)
    op.create_index('idx_lo3so_province_number_date', 'lo_3_so_history', ['province_code', 'number', 'draw_date'], unique=False)
    op.create_index('idx_lo3so_region_number_date', 'lo_3_so_history', ['region', 'number', 'draw_date'], unique=False)
    op.create_index(op.f('ix_lo_3_so_history_draw_date'), 'lo_3_so_history', ['draw_date'], unique=False)
    op.create_index(op.f('ix_lo_3_so_history_id'), 'lo_3_so_history', ['id'], unique=False)
    op.create_index(op.f('ix_lo_3_so_history_lottery_result_id'), 'lo_3_so_history', ['lottery_result_id'], unique=False)
    op.create_index(op.f('ix_lo_3_so_history_number'), 'lo_3_so_history', ['number'], unique=False)
    op.create_index(op.f('ix_lo_3_so_history_province_code'), 'lo_3_so_history', ['province_code'], unique=False)
    op.create_index(op.f('ix_lo_3_so_history_region'), 'lo_3_so_history', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lo_3_so_history_region'), table_name='lo_3_so_history')
    op.drop_index(op.f('ix_lo_3_so_history_province_code'), table_name='lo_3_so_history')
    op.drop_index(op.f('ix_lo_3_so_history_number'), table_name='lo_3_so_history')
    op.drop_index(op.f('ix_lo_3_so_history_lottery_result_id'), table_name='lo_3_so_history')
    op.drop_index(op.f('ix_lo_3_so_history_id'), table_name='lo_3_so_history')
    op.drop_index(op.f('ix_lo_3_so_history_draw_date'), table_name='lo_3_so_history')
    op.drop_index('idx_lo3so_region_number_date', table_name='lo_3_so_history')
    op.drop_index('idx_lo3so_province_number_date', table_name='lo_3_so_history')
    op.drop_index('idx_lo3so_number_date', table_name='lo_3_so_history')
    op.drop_index('idx_lo3so_draw_date_number', table_name='lo_3_so_history')
    op.drop_table('lo_3_so_history')
    op.drop_table('users')
    # ### end Alembic commands ###
